USE [master]
GO
/****** Object:  Database [GearCrawler]    Script Date: 28-Oct-18 07:55:14 PM ******/
CREATE DATABASE [GearCrawler]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GearCrawler', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GearCrawler.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GearCrawler_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\GearCrawler_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [GearCrawler] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GearCrawler].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GearCrawler] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GearCrawler] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GearCrawler] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GearCrawler] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GearCrawler] SET ARITHABORT OFF 
GO
ALTER DATABASE [GearCrawler] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GearCrawler] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GearCrawler] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GearCrawler] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GearCrawler] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GearCrawler] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GearCrawler] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GearCrawler] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GearCrawler] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GearCrawler] SET  DISABLE_BROKER 
GO
ALTER DATABASE [GearCrawler] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GearCrawler] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GearCrawler] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GearCrawler] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GearCrawler] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GearCrawler] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [GearCrawler] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GearCrawler] SET RECOVERY FULL 
GO
ALTER DATABASE [GearCrawler] SET  MULTI_USER 
GO
ALTER DATABASE [GearCrawler] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GearCrawler] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GearCrawler] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GearCrawler] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GearCrawler] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GearCrawler] SET QUERY_STORE = OFF
GO
USE [GearCrawler]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [GearCrawler]
GO
/****** Object:  Table [dbo].[Headset]    Script Date: 28-Oct-18 07:55:14 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Headset](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
 CONSTRAINT [PK_Headset] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Keyboard]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Keyboard](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[NumberOfKeys] [nvarchar](250) NULL,
	[PressForce] [nvarchar](250) NULL,
	[Distance] [nvarchar](250) NULL,
	[LED] [nvarchar](250) NULL,
	[Weight] [nvarchar](250) NULL,
	[Size] [nvarchar](250) NULL,
	[Switches] [nvarchar](250) NULL,
 CONSTRAINT [PK_Keyboard] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Laptop]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Laptop](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[CPU] [nvarchar](250) NULL,
	[GPU] [nvarchar](250) NULL,
	[RAM] [nvarchar](250) NULL,
	[HardDrive] [nvarchar](250) NULL,
	[Monitor] [nvarchar](250) NULL,
	[Ports] [nvarchar](250) NULL,
	[Lan] [nvarchar](250) NULL,
	[Wireless] [nvarchar](250) NULL,
 CONSTRAINT [PK_Laptop] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Mouse]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Mouse](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductId] [int] NOT NULL,
	[Weight] [nvarchar](250) NULL,
	[MaxDPI] [nvarchar](250) NULL,
	[LED] [nvarchar](250) NULL,
	[NumberOfButton] [nvarchar](250) NULL,
 CONSTRAINT [PK_Mouse] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Order]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Order](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CustomerName] [nvarchar](250) NULL,
	[TotalPrice] [bigint] NULL,
 CONSTRAINT [PK_Order] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OrderDetails]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OrderDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderId] [int] NOT NULL,
	[ProductId] [int] NOT NULL,
	[Price] [int] NOT NULL,
 CONSTRAINT [PK_OrderDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ProductTypeId] [int] NOT NULL,
	[HashCode] [int] NOT NULL,
	[Name] [nvarchar](200) NOT NULL,
	[Image] [varchar](250) NOT NULL,
	[Price] [int] NULL,
	[ProductLink] [varchar](250) NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductType]    Script Date: 28-Oct-18 07:55:15 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TypeName] [nchar](30) NOT NULL,
 CONSTRAINT [PK_ProductType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Headset]  WITH CHECK ADD  CONSTRAINT [FK_Headset_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[Headset] CHECK CONSTRAINT [FK_Headset_Product]
GO
ALTER TABLE [dbo].[Keyboard]  WITH CHECK ADD  CONSTRAINT [FK_Keyboard_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[Keyboard] CHECK CONSTRAINT [FK_Keyboard_Product]
GO
ALTER TABLE [dbo].[Laptop]  WITH CHECK ADD  CONSTRAINT [FK_Laptop_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[Laptop] CHECK CONSTRAINT [FK_Laptop_Product]
GO
ALTER TABLE [dbo].[Mouse]  WITH CHECK ADD  CONSTRAINT [FK_Mouse_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[Mouse] CHECK CONSTRAINT [FK_Mouse_Product]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Order] FOREIGN KEY([OrderId])
REFERENCES [dbo].[Order] ([Id])
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_Order]
GO
ALTER TABLE [dbo].[OrderDetails]  WITH CHECK ADD  CONSTRAINT [FK_OrderDetails_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[OrderDetails] CHECK CONSTRAINT [FK_OrderDetails_Product]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_ProductType] FOREIGN KEY([ProductTypeId])
REFERENCES [dbo].[ProductType] ([Id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Product_ProductType]
GO
USE [master]
GO
ALTER DATABASE [GearCrawler] SET  READ_WRITE 
GO
